### ISSUE TITLE
상황별 코디 판별 UI 페이지 생성

### ISSUE THREAD

**Issue by bboroin** [Capstone-Clothing/CODINAVI#16]
## 어떤 기능인지?
> 의류 촬영하기 안에서 상황별 코디 판별 버튼을 통해 연결된 페이지 기능 총 n개의 상황별 키워드를 나열하고 특정 키워드 버튼을 눌렀을 때 인식된 의류가 해당 상황에 맞는 의류인지 판별하고, 해당 상황의 정형화된 옷차림을 알려줌

## 작업 상세 내용
- [x] 상황별 코디 판별 기능 피그마
- [x] Search_Occasion UI
- [x] #22
- [x] Camera 화면 수정 (화면 재구성 및 상황별 코디 판별 버튼 추가)

**Comment by bboroin** [comment]
#22

**Comment by roin0917** [comment]
#22
